"""La migration additive (point 32) et son refus du non-additif.

Une migration additive rattrape une COLONNE, jamais son CONTENU : les
enregistrements antérieurs restent vides et sont COMPTÉS au démarrage.
Un `DEFAULT CURRENT_TIMESTAMP` daterait d'aujourd'hui les commandes
d'avant-hier — une base qui MENT, pire qu'une case vide (point 89)."""

class MigrationsRuntimeMixin:
    """La migration additive (point 32) et son refus du non-additif."""

    def _generate_database_runtime_lines(self):
        """Lignes générées pour le socle DB et les migrations explicites."""
        system_tables = [
            "_monl_users", "_monl_revoked_tokens", "_monl_rate_limit",
            "_monl_sequences", "_monl_migrations",
        ]
        if self.auth_features.get("lockout"):
            system_tables.append("_monl_account_lockouts")
        if self.auth_features.get("password_reset"):
            system_tables.append("_monl_password_reset_tokens")
        if self.auth_features.get("refresh_tokens"):
            system_tables.append("_monl_refresh_tokens")
        system_tables_literal = ", ".join(repr(table) for table in system_tables)
        totp_migration_lines = []
        if self.auth_features.get("totp"):
            totp_migration_lines = [
                "            # BRIQUE B4 : les colonnes TOTP restent NULL pour les comptes",
                "            # historiques ; elles sont comptées, jamais remplies au démarrage.",
                "            _totp_columns = _table_columns(_sys_cur, '_monl_users')",
                "            for _name, _type in (('totp_secret', 'VARCHAR(64)'), ('totp_enabled', 'BOOLEAN'), ('totp_last_step', 'BIGINT')):",
                "                if _name not in _totp_columns:",
                "                    _sys_cur.execute(f'ALTER TABLE _monl_users ADD COLUMN {_name} {_type}')",
                "                    print(f'🔧 Migration : colonne \"{_name}\" ajoutée à \"_monl_users\" ({_type}).')",
                "            conn.commit()",
                '            _sans_totp = conn.execute("SELECT COUNT(*) FROM _monl_users WHERE totp_secret IS NULL").fetchone()[0]',
                "            if _sans_totp:",
                "                print(f\"ℹ️ {_sans_totp} compte(s) restent sans double facteur TOTP : aucune activation n\\'est inventée.\")",
            ]
        return (self._lignes_de_migration(system_tables_literal)
                + self._lignes_de_base(totp_migration_lines))

    def _lignes_de_migration(self, system_tables_literal):
        """Les primitives de migration : empreinte, différences, refus, ALTER."""
        return [
            "def _table_exists(cursor, table):",
            "    if _DATABASE_KIND == 'postgresql':",
            "        cursor.execute('SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?', (table,))",
            "    else:",
            "        cursor.execute('SELECT name FROM sqlite_master WHERE type=\"table\" AND name=?', (table,))",
            "    return cursor.fetchone() is not None",
            "",
            "def _table_column_types(cursor, table):",
            "    if _DATABASE_KIND == 'postgresql':",
            "        cursor.execute('SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ?', (table,))",
            "        return {row[0]: row[1] for row in cursor.fetchall()}",
            "    cursor.execute(f'PRAGMA table_info(\"{table}\")')",
            "    return {row[1]: row[2] for row in cursor.fetchall()}",
            "",
            "def _table_columns(cursor, table):",
            "    return set(_table_column_types(cursor, table))",
            "",
            "def _normalize_sql_type(value):",
            "    value = re.sub(r'\\s+', ' ', (value or '').upper().strip())",
            "    if value.startswith(('CHARACTER VARYING', 'VARCHAR')):",
            "        return 'VARCHAR'",
            "    if value.startswith('DOUBLE PRECISION'):",
            "        return 'DOUBLE PRECISION'",
            "    if value.startswith('TIMESTAMP'):",
            "        return 'TIMESTAMP'",
            "    if value.startswith('NUMERIC'):",
            "        return 'NUMERIC'",
            "    return value.split('(', 1)[0]",
            "",
            "def _schema_fingerprint(conn):",
            "    _cur = conn.cursor()",
            f"    _tables = sorted(set(_EXPECTED_COLUMNS) | {{{system_tables_literal}}})",
            "    _snapshot = {}",
            "    for _table in _tables:",
            "        if _table_exists(_cur, _table):",
            "            _snapshot[_table] = sorted((name, _normalize_sql_type(type_)) for name, type_ in _table_column_types(_cur, _table).items())",
            "    return hashlib.sha256(json.dumps(_snapshot, sort_keys=True, ensure_ascii=False).encode('utf-8')).hexdigest()",
            "",
            "def _ensure_migration_table(conn):",
            "    if _table_exists(conn.cursor(), '_monl_migrations'):",
            "        return",
            "    _identity = ('INTEGER GENERATED BY DEFAULT AS IDENTITY' if _DATABASE_KIND == 'postgresql' else 'INTEGER PRIMARY KEY AUTOINCREMENT')",
            "    conn.execute(f'''CREATE TABLE _monl_migrations (",
            "        id {_identity},",
            "        migration_name VARCHAR(255) NOT NULL,",
            "        operation_index INTEGER NOT NULL,",
            "        operation VARCHAR(64) NOT NULL,",
            "        table_name VARCHAR(255) NOT NULL,",
            "        direction VARCHAR(8) NOT NULL,",
            "        details TEXT NOT NULL,",
            "        applied_at TIMESTAMP NOT NULL,",
            "        schema_fingerprint VARCHAR(64) NOT NULL",
            "    )''')",
            "",
            "def _migration_history_state(conn, name):",
            "    _rows = conn.execute('SELECT operation_index, direction FROM _monl_migrations WHERE migration_name = ? ORDER BY id', (name,)).fetchall()",
            "    _latest = {}",
            "    for _index, _direction in _rows:",
            "        _latest[_index] = _direction",
            "    return _latest",
            "",
            "def _migration_is_applied(conn, migration):",
            "    _state = _migration_history_state(conn, migration['name'])",
            "    return bool(migration['operations']) and all(_state.get(index) == 'up' for index in range(1, len(migration['operations']) + 1))",
            "",
            "def _record_migration(conn, name, index, operation, direction, details):",
            "    conn.execute('INSERT INTO _monl_migrations (migration_name, operation_index, operation, table_name, direction, details, applied_at, schema_fingerprint) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', (",
            "        name, index, operation['kind'], operation['table'], direction,",
            "        json.dumps(operation, sort_keys=True, ensure_ascii=False),",
            "        datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='milliseconds'),",
            "        _schema_fingerprint(conn)))",
            "",
            "def _schema_differences(conn):",
            "    _missing, _extra, _types = [], [], []",
            "    _cur = conn.cursor()",
            "    for _table, _expected in _EXPECTED_COLUMNS.items():",
            "        if not _table_exists(_cur, _table):",
            "            continue",
            "        _actual = _table_column_types(_cur, _table)",
            "        _actual.pop('id', None)",
            "        _expected_map = dict(_expected)",
            "        _missing.extend((_table, _col, _type_) for _col, _type_ in _expected if _col not in _actual)",
            "        _extra.extend((_table, _col) for _col in _actual if _col not in _expected_map)",
            "        _types.extend((_table, _col, _actual[_col], _expected_map[_col]) for _col in _actual if _col in _expected_map and _normalize_sql_type(_actual[_col]) != _normalize_sql_type(_expected_map[_col]))",
            "    return _missing, _extra, _types",
            "",
            "def _migration_for_rename(table, old, new):",
            "    for _migration in _MIGRATIONS:",
            "        for _operation in _migration['operations']:",
            "            if (_operation['kind'] == 'rename' and _operation['table'] == table and _operation['old'] == old and _operation['new'] == new):",
            "                return _migration['name']",
            "    return None",
            "",
            "def _migration_for_drop(table, old):",
            "    for _migration in _MIGRATIONS:",
            "        for _operation in _migration['operations']:",
            "            if _operation['kind'] == 'drop' and _operation['table'] == table and _operation['old'] == old:",
            "                return _migration['name']",
            "    return None",
            "",
            "def _migration_for_type(table, field, actual, expected):",
            "    _actual = _normalize_sql_type(actual)",
            "    _expected = _normalize_sql_type(expected)",
            "    for _migration in _MIGRATIONS:",
            "        for _operation in _migration['operations']:",
            "            if (_operation['kind'] == 'alter' and _operation['table'] == table and _operation['field'] == field and _normalize_sql_type(_operation['from_sql_type']) == _actual and _normalize_sql_type(_operation['to_sql_type']) == _expected):",
            "                return _migration['name']",
            "    return None",
            "",
            "def _refuser_schema_non_additif(conn, missing, extra, types):",
            "    _messages = []",
            "    for _table, _field, _actual, _expected in types:",
            "        _name = _migration_for_type(_table, _field, _actual, _expected)",
            "        _suffix = f\" Exécuter : monl migrate . --name {_name}\" if _name else \" Aucun 'alter ... from ... to ...' déclaré ne permet de l'appliquer automatiquement.\"",
            "        _messages.append(f\"type de {_table}.{_field} : base={_actual}, spec={_expected}.{_suffix}\")",
            "    for _table, _field in extra:",
            "        _renames = [(_new, _migration_for_rename(_table, _field, _new)) for _t, _new, _type_ in missing if _t == _table and _migration_for_rename(_table, _field, _new)]",
            "        if _renames:",
            "            _new, _name = _renames[0]",
            "            _messages.append(f\"renommage non appliqué : {_table}.{_field} -> {_table}.{_new} (migration '{_name}'). Exécuter : monl migrate . --name {_name}\")",
            "        else:",
            "            _name = _migration_for_drop(_table, _field)",
            "            _suffix = f\" Exécuter : monl migrate . --name {_name}\" if _name else \" Aucun 'drop' explicite ne permet de supprimer cette colonne.\"",
            "            _messages.append(f\"colonne retirée de la spec mais encore présente : {_table}.{_field}.{_suffix}\")",
            "    if extra and missing and not any('renommage non appliqué' in _message for _message in _messages):",
            "        _messages.append('Une suppression et un ajout ne prouvent pas un renommage : aucune correspondance n\\'est devinée.')",
            "    if _messages:",
            "        print('❌ Schéma non additif détecté :')",
            "        for _message in _messages:",
            "            print(f'   {_message}')",
            "        raise RuntimeError('Démarrage refusé : migration non additive requise ; la base ne sera pas servie.')",
            "",
            "def _sqlite_replace_column_type(create_sql, field, old_type, new_type):",
            "    _start, _end = create_sql.find('('), create_sql.rfind(')')",
            "    if _start < 0 or _end <= _start:",
            "        raise RuntimeError(f\"CREATE TABLE introuvable pour la migration de {field}.\")",
            "    _body, _parts, _depth, _last = create_sql[_start + 1:_end], [], 0, 0",
            "    for _position, _char in enumerate(_body):",
            "        if _char == '(':",
            "            _depth += 1",
            "        elif _char == ')':",
            "            _depth -= 1",
            "        elif _char == ',' and _depth == 0:",
            "            _parts.append(_body[_last:_position]); _last = _position + 1",
            "    _parts.append(_body[_last:])",
            "    _pattern = re.compile(r'(^\\s*\"' + re.escape(field) + r'\"\\s+)' + re.escape(old_type), re.I)",
            "    for _index, _part in enumerate(_parts):",
            "        _new_part, _count = _pattern.subn(r'\\g<1>' + new_type, _part, count=1)",
            "        if _count:",
            "            _parts[_index] = _new_part",
            "            return create_sql[:_start + 1] + ','.join(_parts) + create_sql[_end:]",
            "    raise RuntimeError(f\"Impossible de remplacer le type de {field} dans le SQL SQLite existant.\")",
            "",
            "def _sqlite_alter_type(conn, table, field, old_type, new_type):",
            "    _row = conn.execute(\"SELECT sql FROM sqlite_master WHERE type='table' AND name=?\", (table,)).fetchone()",
            "    if not _row or not _row[0]:",
            "        raise RuntimeError(f\"SQL de la table SQLite '{table}' introuvable.\")",
            "    _indexes = [row[0] for row in conn.execute(\"SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL\", (table,)).fetchall()]",
            "    _columns = list(_table_column_types(conn.cursor(), table))",
            "    _temporary = '__monl_type_' + secrets.token_hex(5)",
            "    _create = _sqlite_replace_column_type(_row[0], field, old_type, new_type)",
            "    conn.execute('PRAGMA foreign_keys = OFF')",
            "    try:",
            "        conn.execute(f'ALTER TABLE \"{table}\" RENAME TO \"{_temporary}\"')",
            "        conn.execute(_create)",
            "        _names = ', '.join(f'\"{_column}\"' for _column in _columns)",
            "        conn.execute(f'INSERT INTO \"{table}\" ({_names}) SELECT {_names} FROM \"{_temporary}\"')",
            "        conn.execute(f'DROP TABLE \"{_temporary}\"')",
            "        for _index_sql in _indexes:",
            "            conn.execute(_index_sql)",
            "    finally:",
            "        conn.execute('PRAGMA foreign_keys = ON')",
            "",
            "def _apply_migration_operation(conn, operation, direction):",
            "    _table, _kind = operation['table'], operation['kind']",
            "    if not _table_exists(conn.cursor(), _table):",
            "        raise RuntimeError(f\"Table '{_table}' absente : précondition de migration impossible.\")",
            "    _types = _table_column_types(conn.cursor(), _table)",
            "    if _kind == 'rename':",
            "        _old, _new = (operation['old'], operation['new']) if direction == 'up' else (operation['new'], operation['old'])",
            "        if _old not in _types or _new in _types:",
            "            raise RuntimeError(f\"Précondition du renommage {_table}.{_old} -> {_table}.{_new} non satisfaite (colonnes présentes : {sorted(_types)}).\")",
            "        conn.execute(f'ALTER TABLE \"{_table}\" RENAME COLUMN \"{_old}\" TO \"{_new}\"')",
            "        return",
            "    if _kind == 'drop':",
            "        if direction != 'up':",
            "            raise RuntimeError(f\"La suppression de {_table}.{operation['old']} est irréversible sans sauvegarde ; aucune descente ne sera prétendue.\")",
            "        _old = operation['old']",
            "        if _old not in _types:",
            "            raise RuntimeError(f\"Précondition du DROP {_table}.{_old} non satisfaite.\")",
            "        conn.execute(f'ALTER TABLE \"{_table}\" DROP COLUMN \"{_old}\"')",
            "        return",
            "    _field = operation['field']",
            "    _source = operation['from_sql_type'] if direction == 'up' else operation['to_sql_type']",
            "    _target = operation['to_sql_type'] if direction == 'up' else operation['from_sql_type']",
            "    if _field not in _types or _normalize_sql_type(_types[_field]) != _normalize_sql_type(_source):",
            "        raise RuntimeError(f\"Précondition du changement de type {_table}.{_field} non satisfaite (base={_types.get(_field)!r}, attendu={_source!r}).\")",
            "    if _DATABASE_KIND == 'postgresql':",
            "        conn.execute(f'ALTER TABLE \"{_table}\" ALTER COLUMN \"{_field}\" TYPE {_target} USING \"{_field}\"::{_target}')",
            "    else:",
            "        _sqlite_alter_type(conn, _table, _field, _types[_field], _target)",
            "",
        ]
