"""WAL, verrou passager, préparation de la base, `init_db`.

Le socle ne sème que dans une table VIDE : c'est pourquoi un rattachement
de `seed` se résout au DÉMARRAGE et non à la compilation (point 100)."""

class PreparationRuntimeMixin:
    """WAL, verrou passager, préparation de la base, `init_db`."""

    def _lignes_de_base(self, totp_migration_lines):
        """Le socle : WAL, verrou passager, préparation, application, init_db."""
        return [
            "def _activer_wal(conn):",
            "    \"\"\"Bascule en WAL sans jamais faire échouer le démarrage.",
            "",
            "    Le mode de journal est une propriété PERSISTANTE du FICHIER,",
            "    pas de la connexion : le premier processus qui y arrive le",
            "    règle pour tous les suivants. Or ce pragma est le seul endroit",
            "    du socle que `busy_timeout` ne protège PAS — mesuré, pas",
            "    supposé : face à une transaction de lecture concurrente il",
            "    attend le délai entier puis échoue quand même, et face à une",
            "    transaction d'ÉCRITURE il échoue en 0,00 s. Démarré avec",
            "    `--workers 2`, un worker écrivait le schéma pendant que",
            "    l'autre exécutait ce pragma : le second mourait, et uvicorn",
            "    arrêtait le serveur entier.",
            "",
            "    Échouer ici ne coûte que de la concurrence, jamais une",
            "    donnée : sans WAL la base retombe sur le journal de",
            "    restauration, qui est le mode par défaut de SQLite.",
            "    \"\"\"",
            "    try:",
            "        conn.execute('PRAGMA journal_mode = WAL')",
            "    except sqlite3.OperationalError:",
            "        pass",
            "",
            "def _verrou_passager(erreur):",
            "    \"\"\"Cette erreur dit-elle « quelqu'un d'autre écrit en ce moment » ?",
            "",
            "    Distinguer importe : un verrou passager se réessaie, un schéma",
            "    fautif doit remonter tout de suite. Réessayer une vraie erreur",
            "    de schéma ne ferait que retarder le diagnostic de vingt",
            "    secondes.",
            "    \"\"\"",
            "    return (isinstance(erreur, sqlite3.OperationalError)",
            "            and ('locked' in str(erreur).lower()",
            "                 or 'busy' in str(erreur).lower()))",
            "",
            "def _prepare_database(conn):",
            "    if _DATABASE_KIND == 'sqlite':",
            "        _activer_wal(conn)",
            "    # RÉESSAI PLUTÔT QU'INSTRUCTION PAR INSTRUCTION. `busy_timeout`",
            "    # ne couvre ni le changement de mode de journal ni le COMMIT",
            "    # implicite d'`executescript` — corriger la seule instruction",
            "    # observée laisserait la suivante tomber au prochain démarrage",
            "    # concurrent. Le DDL du socle est idempotent (CREATE TABLE IF",
            "    # NOT EXISTS), donc le rejouer ne coûte rien.",
            "    _limite = time.time() + 20.0",
            "    while True:",
            "        try:",
            "            with open('schema.sql', 'r', encoding='utf-8') as _file:",
            "                conn.executescript(_schema_for_database(_file.read()))",
            "            _ensure_migration_table(conn)",
            "            conn.commit()",
            "            return",
            "        except Exception as _error:",
            "            try:",
            "                conn.rollback()",
            "            except Exception:",
            "                pass",
            "            if _verrou_passager(_error) and time.time() < _limite:",
            "                time.sleep(0.25)",
            "                continue",
            "            raise RuntimeError(f'Initialisation du schéma échouée : {_error}') from _error",
            "",
            "def apply_migration(name, direction='up'):",
            "    if direction not in ('up', 'down'):",
            "        raise ValueError(\"direction de migration inconnue\")",
            "    conn = _connect()",
            "    try:",
            "        _prepare_database(conn)",
            "        _migration = next((_item for _item in _MIGRATIONS if _item['name'] == name), None)",
            "        if _migration is None:",
            "            raise RuntimeError(f\"Migration inconnue : '{name}'.\")",
            "        if direction == 'up' and _migration_is_applied(conn, _migration):",
            "            raise RuntimeError(f\"Migration déjà appliquée : '{name}'.\")",
            "        if direction == 'down' and not _migration_is_applied(conn, _migration):",
            "            raise RuntimeError(f\"Migration non appliquée : '{name}'.\")",
            "        if direction == 'down' and any(not _item['reversible'] for _item in _migration['operations']):",
            "            raise RuntimeError(f\"La migration '{name}' contient un DROP irréversible sans sauvegarde ; la descente est refusée.\")",
            "        conn.execute('BEGIN')",
            "        _items = list(enumerate(_migration['operations'], start=1))",
            "        if direction == 'down':",
            "            _items.reverse()",
            "        for _index, _operation in _items:",
            "            _apply_migration_operation(conn, _operation, direction)",
            "            _record_migration(conn, name, _index, _operation, direction, _operation)",
            "        conn.commit()",
            "        print(f\"✅ Migration '{name}' ({direction}) appliquée. Empreinte : {_schema_fingerprint(conn)}\")",
            "    except Exception:",
            "        conn.rollback()",
            "        raise",
            "    finally:",
            "        conn.close()",
            "",
            "def init_db():",
            "    conn = _connect()",
            "    try:",
            "        _prepare_database(conn)",
            "        _missing, _extra, _types = _schema_differences(conn)",
            "        _refuser_schema_non_additif(conn, _missing, _extra, _types)",
            "        _cur = conn.cursor()",
            "        if _missing:",
            "            conn.execute('BEGIN')",
            "        for _auto_index, (_table, _col, _sql_type) in enumerate(_missing, start=1):",
            "            _cur.execute(f'ALTER TABLE \"{_table}\" ADD COLUMN \"{_col}\" {_sql_type}')",
            "            _record_migration(conn, '__auto_add_column__', _auto_index, {'kind': 'add_column', 'table': _table, 'column': _col, 'sql_type': _sql_type}, 'up', {'table': _table, 'column': _col, 'sql_type': _sql_type})",
            "            print(f'🔧 Migration additive : colonne \"{_col}\" ajoutée à \"{_table}\" ({_sql_type}).')",
            "        if _missing:",
            "            conn.commit()",
            "        for _table, _col, _index in _UNIQUE_INDEXES:",
            "            try:",
            "                conn.execute(f'CREATE UNIQUE INDEX IF NOT EXISTS \"{_index}\" ON \"{_table}\" (\"{_col}\")')",
            "                conn.commit()",
            "            except _DATABASE_INTEGRITY_ERRORS:",
            "                conn.rollback()",
            "                _dups = conn.execute(f'SELECT COUNT(*) FROM (SELECT \"{_col}\" FROM \"{_table}\" GROUP BY \"{_col}\" HAVING COUNT(*) > 1)').fetchone()[0]",
            "                print(f'❌ \"{_table}\".\"{_col}\" est déclaré unique dans la spec, mais la base contient déjà {_dups} valeur(s) en double : l\\'unicité NE PEUT PAS être appliquée. Dédoublonner, puis redémarrer (docs/MIGRATIONS.md).')",
            "            except Exception as _error:",
            "                conn.rollback()",
            "                print(f'⚠️ Index unique sur \"{_table}\".\"{_col}\" non appliqué : {_error}')",
            "        for _table, _cols, _index in _ONCE_PER_INDEXES:",
            "            try:",
            "                _columns = ', '.join(f'\"{_col}\"' for _col in _cols)",
            "                conn.execute(f'CREATE UNIQUE INDEX IF NOT EXISTS \"{_index}\" ON \"{_table}\" ({_columns})')",
            "                conn.commit()",
            "            except _DATABASE_INTEGRITY_ERRORS:",
            "                conn.rollback()",
            "                print(f'❌ Unicité métier déjà violée sur \"{_table}\" ({_columns}) : corriger les doublons avant de redémarrer.')",
            "            except Exception as _error:",
            "                conn.rollback()",
            "                print(f'⚠️ Index oncePer sur \"{_table}\" non appliqué : {_error}')",
            "        for _table, _col in _TIMESTAMP_COLUMNS:",
            "            _sans = conn.execute(f'SELECT COUNT(*) FROM \"{_table}\" WHERE \"{_col}\" IS NULL').fetchone()[0]",
            "            if _sans:",
            "                print(f'ℹ️ \"{_table}\".\"{_col}\" : {_sans} enregistrement(s) créé(s) avant l\\'ajout de l\\'horodatage restent sans date. Elle ne peut pas être reconstituée — les dater après coup serait faux.')",
            "        for _table, _col in _NUMBERED_COLUMNS:",
            "            _sans = conn.execute(f'SELECT COUNT(*) FROM \"{_table}\" WHERE \"{_col}\" IS NULL').fetchone()[0]",
            "            if _sans:",
            "                print(f'ℹ️ \"{_table}\".\"{_col}\" : {_sans} enregistrement(s) créé(s) avant l\\'ajout de la numérotation restent sans numéro. La séquence repart de 1 ; leur attribuer un numéro maintenant inventerait un ordre d\\'arrivée.')",
            "        if AUTH_IDENTIFIER_FORMS and 'libre' not in AUTH_IDENTIFIER_FORMS:",
            "            _anciens = [r[0] for r in conn.execute('SELECT username FROM _monl_users').fetchall()]",
            "            _hors = [u for u in _anciens if not _forme_valide(u)]",
            "            if _hors:",
            "                print(f'ℹ️ {len(_hors)} compte(s) existant(s) ne suivent pas la forme d\\'identifiant déclarée ({\", \".join(AUTH_IDENTIFIER_FORMS)}) : {\", \".join(_hors[:5])}{\"…\" if len(_hors) > 5 else \"\"}. Ils continuent de fonctionner ; la règle ne vaut que pour les inscriptions à venir.')",
            "        try:",
            "            _sys_cur = conn.cursor()",
            "            if not _table_exists(_sys_cur, '_monl_revoked_tokens'):",
            "                raise RuntimeError('table _monl_revoked_tokens absente')",
            "            if 'expires_at' not in _table_columns(_sys_cur, '_monl_revoked_tokens'):",
            "                _sys_cur.execute('ALTER TABLE _monl_revoked_tokens ADD COLUMN expires_at DOUBLE PRECISION')",
            "                _record_migration(conn, '__auto_system__', 1, {'kind': 'add_column', 'table': '_monl_revoked_tokens', 'column': 'expires_at', 'sql_type': 'DOUBLE PRECISION'}, 'up', {'table': '_monl_revoked_tokens', 'column': 'expires_at'})",
            "            _purge_revoked_tokens(_sys_cur)",
            *totp_migration_lines,
            "            conn.commit()",
            "        except Exception:",
            "            conn.rollback()",
            "            raise",
            "        try:",
            "            _scur = conn.cursor()",
            "            for _table, _rows in _SEED_DATA.items():",
            "                _scur.execute(f'SELECT COUNT(*) FROM \"{_table}\"')",
            "                if _scur.fetchone()[0] > 0:",
            "                    continue",
            "                _poses = 0",
            "                for _entree in _rows:",
            "                    _row = dict(_entree['values'])",
            "                    _p = _entree.get('parent')",
            "                    if _p:",
            "                        _scur.execute(f'SELECT id FROM \"{_p[\"table\"]}\" WHERE \"{_p[\"field\"]}\" = ?', (_p['value'],))",
            "                        _cible = _scur.fetchone()",
            "                        if not _cible:",
            "                            print(f'⚠️ Donnée de démonstration ignorée : aucun \"{_p[\"table\"]}\" dont {_p[\"field\"]} vaut \"{_p[\"value\"]}\" pour y rattacher une ligne de \"{_table}\".')",
            "                            continue",
            "                        _row[_p['column']] = _cible[0]",
            "                    _cols = list(_row.keys())",
            "                    _placeholders = ', '.join(['?'] * len(_cols))",
            "                    _colnames = ', '.join(f'\"{_c}\"' for _c in _cols)",
            "                    _scur.execute(f'INSERT INTO \"{_table}\" ({_colnames}) VALUES ({_placeholders})', tuple(_row.values()))",
            "                    _poses += 1",
            "                if _poses:",
            "                    print(f'🌱 Données de démonstration insérées dans \"{_table}\" ({_poses}).')",
            "            conn.commit()",
            "        except Exception as _error:",
            "            conn.rollback()",
            "            print(f'⚠️ Données de démonstration ignorées : {_error}')",
            "    except Exception:",
            "        conn.rollback()",
            "        raise",
            "    finally:",
            "        conn.close()\n",
        ]
