"""Ce qu'une passe doit savoir faire, et ce que le pilote attend d'elle."""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Protocol


class ValidationContext(Protocol):
    """Surface dont les passes actuelles ont besoin."""

    def _valider_contraintes_de_champ(self) -> None: ...

    def _valider_controle_dacces(self) -> None: ...

    def _valider_regle_public(self) -> None: ...

    def _valider_regles_once_per(self) -> None: ...

    def _valider_regle_restrictedTo(self) -> None: ...

    def _valider_champs_masques(self) -> None: ...

    def _valider_champs_categorises(self) -> None: ...

    def _valider_champs_generes(self) -> None: ...

    def _valider_champs_horodates(self) -> None: ...

    def _valider_champs_numerotes(self) -> None: ...

    def _valider_champs_enumeres(self) -> None: ...

    def _valider_capacites_de_liste(self) -> None: ...

    def _valider_requires_own_et_payable(self) -> None: ...

    def _valider_champs_derives(self) -> None: ...

    def _valider_champs_agreges(self) -> None: ...

    def _valider_securite_calculs_paiement(self) -> None: ...

    def _valider_effets_compteurs(self) -> None: ...

    def _valider_proprietaire_paiement(self) -> None: ...

    def _valider_regles_liberation(self) -> None: ...

    def _valider_workflows_et_collisions(self) -> None: ...

    def _valider_champs_uploades(self) -> None: ...

    def _valider_ui_overrides(self) -> None: ...

    def _valider_landing(self) -> None: ...

    def _valider_capacites(self) -> None: ...

    def _valider_regles_message(self) -> None: ...

    def _valider_assets_et_seeds(self) -> None: ...

    def _valider_migrations(self) -> None: ...

    def _valider_regle_apres_paiement(self) -> None: ...

    def _audit_security_rules(self) -> list[str]: ...

    def _audit_self_registration(self) -> list[str]: ...

class ValidationPass(Protocol):
    name: str

    def run(self, context: ValidationContext) -> list[str]: ...

@dataclass(frozen=True, slots=True)
class ValidationPipeline:
    passes: Sequence[ValidationPass]

    def run(self, context: ValidationContext) -> list[str]:
        reports = []
        for validation_pass in self.passes:
            reports.extend(validation_pass.run(context))
        return reports
