"""L'ordre par défaut. C'est LUI qui décide quel refus tombe en premier —
et plusieurs points du journal reposent sur cet ordre (le recoupement de
`payable` arrive APRÈS les deux boucles, point 79)."""

from .contrats import ValidationPipeline
from .passes import (
    AccessControlValidationPass,
    AggregatedFieldValidationPass,
    AssetsSeedValidationPass,
    CalculationPaymentSafetyPass,
    CapabilityValidationPass,
    CategorizedFieldValidationPass,
    CounterEffectValidationPass,
    CreationPaymentPrerequisitePass,
    DerivedFieldValidationPass,
    EnumeratedFieldValidationPass,
    FieldConstraintValidationPass,
    GeneratedFieldValidationPass,
    HiddenFieldValidationPass,
    LandingValidationPass,
    ListQueryCapabilityValidationPass,
    MessageRuleValidationPass,
    MigrationValidationPass,
    NumberedFieldValidationPass,
    OncePerValidationPass,
    PayableOwnerValidationPass,
    PostPaymentValidationPass,
    PublicVisibilityValidationPass,
    ReleaseRuleValidationPass,
    RestrictedFieldValidationPass,
    SecurityAuditPass,
    SelfRegistrationAuditPass,
    TimestampFieldValidationPass,
    UIOverrideValidationPass,
    WorkflowCollisionValidationPass,
)

DEFAULT_VALIDATION_PIPELINE = ValidationPipeline((
    FieldConstraintValidationPass(),
    AccessControlValidationPass(),
    PublicVisibilityValidationPass(),
    OncePerValidationPass(),
    RestrictedFieldValidationPass(),
    HiddenFieldValidationPass(),
    CategorizedFieldValidationPass(),
    GeneratedFieldValidationPass(),
    TimestampFieldValidationPass(),
    NumberedFieldValidationPass(),
    EnumeratedFieldValidationPass(),
    ListQueryCapabilityValidationPass(),
    CreationPaymentPrerequisitePass(),
    DerivedFieldValidationPass(),
    AggregatedFieldValidationPass(),
    CalculationPaymentSafetyPass(),
    CounterEffectValidationPass(),
    PayableOwnerValidationPass(),
    ReleaseRuleValidationPass(),
    WorkflowCollisionValidationPass(),
    UIOverrideValidationPass(),
    LandingValidationPass(),
    CapabilityValidationPass(),
    MessageRuleValidationPass(),
    AssetsSeedValidationPass(),
    MigrationValidationPass(),
    PostPaymentValidationPass(),
    SecurityAuditPass(),
    SelfRegistrationAuditPass(),
))
